### ISSUE TITLE
NickServ FREEZE ISSUES

### ISSUE THREAD

**Issue by fuadragon** [atheme/atheme#922]
I used /NickServ FREEZE on a nickname, who was online. Services logged him out, setting -r.
That user didnt get any message what happened. He changed to another nickname, after joined back to Frozen nickname.
Services told, it is registered nickname, please choose another one. It is not right that Services let people to get Frozen nickname and + tell that it is a registered nickname.

if nickname got FREEZE, thats it, finita la comedia. no one can take it, services should send a message to one who types /nick FrozenNickname, as an example, This nickname is frozen and cannot be used.

https://paste.mozilla.org/0zdBVAbw

**Comment by jesopo** [comment]
nicknames being frozen just means that they can't be registered. if you want to prevent someone changing to a nickname that is frozen, try RESV for ircd-ratbox derivatives or QLINE for unrealircd/inspircd

**Comment by fuadragon** [comment]
It doesnt make a sense, if a nickname FROZEN and you can still get that nickname. And it is weird that services let you get it + tell you that it is a registered nickname. When someone tries to get a frozen nickname, services wont allow to get it, sending a message ( this nickname is frozen and cannot be used). Also a user got FROZEN beeing online, without any notification from services. This is also not right thing.

**Comment by aaronmdjones** [comment]
> It doesnt make a sense, if a nickname FROZEN

Nicknames cannot be frozen. NickServ's `FREEZE` feature is to disable an *account*, which is *not* a nickname. Deciding whether you can use a nickname or not is the job of your IRC server, not services; and is accomplished via a `RESV` as Jess pointed out.

I already fixed the NOTICE in commit 266c5a80acfddb48f4b4 several weeks ago.

**Comment by fuadragon** [comment]
> > It doesnt make a sense, if a nickname FROZEN
> 
> Nicknames cannot be frozen. NickServ's `FREEZE` feature is to disable an _account_, which is _not_ a nickname. Deciding whether you can use a nickname or not is the job of your IRC server, not services; and is accomplished via a `RESV` as Jess pointed out.
> 
> I already fixed the NOTICE in commit [266c5a8](https://github.com/atheme/atheme/commit/266c5a80acfddb48f4b4242eaca43fa8f28e7a3d) several weeks ago.



It is NOT fixed, Aaron.  
https://paste.mozilla.org/Ydw46znw

**Comment by fuadragon** [comment]
Ive just newly git clone and testes on it.  ONLINE user didnt even noticed by services that IRC Operator made FREEZE his/her nickname. Just logged out, without any notification and + user still can use FROZEN account by /nick f  + services tell him - -NickServ- This nickname is registered. Please choose a different nickname. <- This is weird actually.

atheme-7.3.0-rc2 services.test.net 9d23473f3bf8c428ff84 ACFHcl [InspIRCd] [enc:crypto/pbkdf2v2] Build Date: Mar  7 2024

**Comment by fuadragon** [comment]
if (metadata_find(mn->owner, "private:freeze:freezer"))
		notice(nicksvs.nick, u->nick, "This nickname is registered. Please choose a different nickname.");

This allow user use Frozen nickname or account whatever. And tells him this nickname is REGISTERED. 
AT LEAST it should say its FROZEN. 
This all works not properly, i would suggest you to check it again.
